insert into AUTHOR (id, name) values (1, 'Machado de Assis');
insert into AUTHOR (id, name) values (2, 'Mia Couto');
insert into AUTHOR (id, name) values (3, 'Isaac Asimov');
insert into POST (id, author_Id, content, date) values ('1', '1', 'Post de Machado de Assis', CURRENT_TIMESTAMP());
insert into POST (id, author_Id, content, date) values ('2', '2', 'Post de Mia Couto', CURRENT_TIMESTAMP());
insert into POST (id, author_Id, content, date)values ('3', '3', 'Post de Isaac Asimov', CURRENT_TIMESTAMP());
insert into COMMENT (id, post_id, content, date)values (1, 3, 'Comentário de Machado de Assis', CURRENT_TIMESTAMP());
insert into COMMENT (id, post_id, content, date)values (2, 3, 'Comentário de Isaac Asimov', CURRENT_TIMESTAMP());
insert into COMMENT (id, post_id, content, date)values (3, 2, 'Comentário de Mia Couto', CURRENT_TIMESTAMP());
call next value for SE_AUTHOR;
call next value for SE_AUTHOR;
call next value for SE_AUTHOR;
call next value for SE_POST;
call next value for SE_POST;
call next value for SE_POST;
call next value for SE_COMMENT;
call next value for SE_COMMENT;
call next value for SE_COMMENT;
